### ISSUE TITLE
[Documentation] Statement of need missing from docs

### ISSUE THREAD

**Issue by cbouysset** [JustinYKC/FEPOPS#12]
Refers to the JOSS submission review: https://github.com/openjournals/joss-reviews/issues/5763

The statement of need that is visible in the paper is missing from the docs and is required to be present in the JOSS checklist.

**Comment by stevenshave** [comment]
Thank you for reviewing our package. I am working through the raised issues and will build a new pypi package once completed.
For this issue I have added the statement of need to the README.md, which is now imported into the docs when built upon commit. This addition was made in 0bffab8.

**Comment by cbouysset** [comment]
Perfect, thanks!
