### ISSUE TITLE
[Documentation] Lack of community guidelines

### ISSUE THREAD

**Issue by cbouysset** [JustinYKC/FEPOPS#13]
Refers to the JOSS submission review: https://github.com/openjournals/joss-reviews/issues/5763

The documentation is missing the following item required by JOSS:
> Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

This usually comes in the form of a `CONTRIBUTING.md` file in the repo that you can then include in the docs. An example of which can be found on the [GitHub docs](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

**Comment by stevenshave** [comment]
Thank you for reviewing our package. I am working through the raised issues and will build a new pypi package once completed.

To address this issue I have added a CONTRIBUTING.md and a CODE_OF_CONDUCT.md. These were added in commit 275da17.

**Comment by cbouysset** [comment]
Thanks!
