### ISSUE TITLE
[Documentation] Tests

### ISSUE THREAD

**Issue by cbouysset** [JustinYKC/FEPOPS#14]
Refers to the JOSS submission review: https://github.com/openjournals/joss-reviews/issues/5763

The source repository contains tests but they are not automatically run by a CI solution, one has to manually run them to confirm that the installation is working correctly and/or that any modification made to the implementation did not break anything.
In its current form the documentation is lacking some instructions on how to run those tests (i.e. pip install pytest and run `pytest tests/`)

I'll also include a minor comment on the tests themselves (optional for you to tackle): in the last test, [that line](https://github.com/JustinYKC/FEPOPS/blob/master/test/tests.py#L62) is not really checking that the results for the persistent fepops storage object are the same, it only compares the keys (molecule names) instead of also comparing the values. It should just be `assert fepops_dict == fepops_dict2`

**Comment by JustinYKC** [comment]
We have now implemented a CI workflow in f0a9f0952a2098d0d70345790c5d48000447cb25 for the master and development branches which runs the black formatter and tests upon push and pull requests. In addition, instructions for running tests have been added to the readme and online documentation. This has been merged into master in 2146bcf0b2737ea671cb4beed6cbfc5632f8baee and is present in OpenFEPOPS v 1.8.0.

**Comment by cbouysset** [comment]
Just a quick note (optional to address) on the CI workflow, on [these lines](https://github.com/JustinYKC/FEPOPS/blob/master/.github/workflows/ci.yaml#L6-L8) the target branch should most likely be `master` instead of `main` (unless you plan on renaming the master branch to main).

**Comment by stevenshave** [comment]
Ah! great catch thank you.  I have fixed this in debfe34cd8ddc306fa981251e8bb59231fea26d2.
