### ISSUE TITLE
[Documentation] API docs section not compiled correctly

### ISSUE THREAD

**Issue by cbouysset** [JustinYKC/FEPOPS#15]
Refers to the JOSS submission review: https://github.com/openjournals/joss-reviews/issues/5763

The [API section](https://justinykc.github.io/FEPOPS/fepops.html) seem to not be compiled correctly as it is not showing the content of the docstrings for the different classes/functions which is a shame since these are very well documented.

Without this it's hard for me to justify that the core functionality of the software is documented to a satisfactory level as users would have trouble accessing it unless they read the source code.

**Comment by JustinYKC** [comment]
This has been corrected in fb7214bb07d07d4c049cc14141cfc14bc2ab4795 which was later merged to master in 2146bcf0b2737ea671cb4beed6cbfc5632f8baee then addressed again in f16d0e1c58005b330b7397fb8c9e1831165f7318 when a conflict arose in sphinx 7.2.5 with Numpy. Sphinx was then pinned to an earlier version. API docs now render correctly and support the OpenFEPOPS v1.8.0 release.
