### ISSUE TITLE
[Software paper] Lacking mention of how features are computed

### ISSUE THREAD

**Issue by cbouysset** [JustinYKC/FEPOPS#16]
Refers to the JOSS submission review: https://github.com/openjournals/joss-reviews/issues/5763

The paper is missing one or two sentences on how the features are computed:

- partial charges: Gasteiger charges calculated with RDKit
- Atomic logP contribution: Crippen method as implemented in RDKit
- Hbond donors and acceptors: SMARTS patterns taken from DAYLIGHT

Since the SMARTS pattern are taken from the [DAYLIGHT website](https://www.daylight.com/dayhtml_tutorials/languages/smarts/smarts_examples.html#H_BOND), they must be added to the references. (and ideally the [RDKit](https://www.rdkit.org/docs/Overview.html#citing-the-rdkit) as well)

**Comment by JustinYKC** [comment]
We have expanded the paper (paper, readme and docs - 6280684620464c95da3f80ff766942eb1c86e472) with an explanation of how atomic properties are calculated with RDKit (ref added) – using the Gasteiger algorithm (reference added) for atomic partial charges, Crippen method (reference added) for atomic logP contributions and referenced the paper from which the HBA+HBD acceptor patterns were taken - https://pubs.acs.org/doi/10.1021/ci970431+ . This has been merged into main in 2146bcf0b2737ea671cb4beed6cbfc5632f8baee and is present in OpenFEPOPS v 1.8.0.

**Comment by cbouysset** [comment]
There seem to be an issue with the reference for Gasteiger charges, it should be [Gasteiger & Marsili](https://doi.org/10.1016/0040-4020(80)80168-2) instead of Wildman & Crippen.

**Comment by stevenshave** [comment]
Thank you, this was certainly an error on my part. The Gasteiger reference has now been properly inserted in 8303a1815f5a176d6c9c6aefcf4d01035d4ee333.
