### ISSUE TITLE
[Installation] Dependencies not installed from pip

### ISSUE THREAD

**Issue by cbouysset** [JustinYKC/FEPOPS#17]
When installing the package with `pip install fepops` the dependencies are not automatically installed alongside the package.

There are alternative installation instructions so this is not blocking for me for the review, but it would be appreciated if this could be fixed in the next release.

I believe the error is in the `pyproject.toml` file and you should move the dependencies under `build-system.requires` to `project.dependencies`, `build-system.requires` should only contain the libraries needed to build the package:

```diff
[project]
+dependencies = [
+    "rdkit>=2021.9.5.1",
+    "numpy>=1.22.4",
+    "pandas>=1.5.0",
+    "scikit-learn>=1.3.0",
+    "scipy>=1.7.0",
+    "torch",
+    "fast-pytorch-kmeans>=0.1.9",
+    "fire>=0.5.0",
+    "tqdm>=4.48.0",
+]

[build-system]
requires=[
    "setuptools>=61.0.0",
-    "rdkit>=2021.9.5.1",
-    "numpy>=1.22.4",
-    "pandas>=1.5.0",
-    "scikit-learn>=1.3.0",
-    "scipy>=1.7.0",
-    "torch",
-    "fast-pytorch-kmeans>=0.1.9",
-    "fire>=0.5.0",
-    "tqdm>=4.48.0",
]
```

**Comment by JustinYKC** [comment]
Thanks for bringing this to our attention.  The issue has now been addressed in ed22de253f2b6fc1aae401a3f56e5e6fae7f2368. The package now installs with pip (from directory, editable mode, and from the whl).  Slightly related is the conda environment file which has also been updated. These changes have been merged into main in 2146bcf0b2737ea671cb4beed6cbfc5632f8baee and are present in OpenFEPOPS v1.8.0.
