### ISSUE TITLE
Profiling

### ISSUE THREAD

**Issue by stevenshave** [JustinYKC/FEPOPS#2]
Profiling needed to understand bottlenecks in code and assess if a Python implementation of FEPOPS is viable, if not then re purpose as a reference implementation and learning resource.

**Comment by JustinYKC** [comment]
This is the results of profiling of the implementation:
![sklearn_1](https://user-images.githubusercontent.com/50987508/221309388-45c4d804-e90e-4111-b66a-271f11504551.png)
![sklearn_table_1](https://user-images.githubusercontent.com/50987508/221309467-61d2e45c-fbc5-443e-808e-f0804b28f146.png)


The process of k-means in scikit-learn is the main bottleneck of the implementation. The original k-means was replaced with the pytorch k-means and the results of profiling were shown below:
![pytorch_cpu_1](https://user-images.githubusercontent.com/50987508/221311280-462ad520-0a78-40fe-b8aa-1b29e89f4c76.png)
![pytorch_cpu_table_1](https://user-images.githubusercontent.com/50987508/221311327-1aee75af-0c8c-4b7f-8d90-ddeb9d13a5d5.png)


The running time of the implementation was greatly decreased by replacing the scikit-learn k-means with the pytorch k-means, from 55.5s to 8.48s. The new implementation with the pytorch k-mean method for tackling the bottleneck has been updated.
