### ISSUE TITLE
[ Installation ] pip installs per default v.1.6.0, issue installing v.1.8.0

### ISSUE THREAD

**Issue by hannahbaumann** [JustinYKC/FEPOPS#21]
When installing fepops with `pip install fepops` it installs fepops v 1.6.0 which doesn't have the dependencies installed alongside the package.

When I try `pip install fepops==1.8.0` I get the following error:
`Collecting fepops==1.8.0
  Obtaining dependency information for fepops==1.8.0 from https://files.pythonhosted.org/packages/1d/8e/72d2c7698ab11a3363eb3275ee5abdd6ec22ae077aec8c857067f030ba84/fepops-1.8.0-py3-none-any.whl.metadata
  Using cached fepops-1.8.0-py3-none-any.whl.metadata (14 kB)
INFO: pip is looking at multiple versions of fepops to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement rdkit>=2021.9.5.1 (from fepops) (from versions: none)
ERROR: No matching distribution found for rdkit>=2021.9.5.1`

Can you reproduce these errors or is this just on my end?

**Comment by stevenshave** [comment]
Thanks for raising this issue and taking the time to look at FEPOPS. I think I have figured out what is going on here and will rebuild the package soon to sort out after some testing.

It looks like rdkit 2021.9.5.1 needed to be installed from the pip package rdkit-pypi.  But the official distribution now looks to be just called "rdkit" in pypi which does not include 2021.9.5.1 release.

I will update to an appropriate release and update the requirements after some testing.

Thanks again, and I will post here when completed.

**Comment by stevenshave** [comment]
This issue has been fixed in the 1.8.1 release of OpenFEPOPS which has now been uploaded to pypi. The issue was indeed the incorrect "rdkit-pypi" package listed in requirements instead of the new official rdkit package of just "rdkit".

I think this was not picked up in the automated CI testing as that installed the optional "dev" version which had the correct "rdkit" dependency.

Many thanks for bringing this to our attention!

**Comment by hannahbaumann** [comment]
Thank you for getting back to me so quickly, I was now able to successfully install it!
